### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by jt3k** [michaelsogos/Hash-Router#2]
https://jsbin.com/behujo/edit?html,js

**Comment by michaelsogos** [comment]
Hi Andrey,

You are using it in the wrong way, take a look to the documentation.

I changed your JS BIN example and:
1. Don't use double hash ## in the url
2. You forgot Router.init()

I tested it in JS BIN 
https://jsbin.com/datoqudipi/edit?html,js,console,output
and in JSFiddle too
http://jsfiddle.net/01aynvf0/10/

Let me know, for now i don't see a bug :)

You are welcome.

**Comment by jt3k** [comment]
thnx! good job!
